// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavdcxubeextjykjnrjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdmRjeHViZWV4dGp5a2pucmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxOTczNTQsImV4cCI6MjA1NDc3MzM1NH0.iegKmsUoDjj4R5MnCAB2fMOwogCgGAO_zqDeNRaWaSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);